#! /usr/bin/env zsh

autoload -Uz compinit	&& compinit
autoload -Uz promptinit && promptinit
autoload -Uz colors	&& colors

setopt COMPLETE_ALIASES

# Always rebuild cache
zstyle ':completion:*' rehash true

# Arrow driven interface
zstyle ':completion:*' menu select

if [ -r "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
	source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
if [ -r "/usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" ]; then
	source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
fi
