#! /usr/bin/env zsh

autoload -Uz compinit	&& compinit
autoload -Uz promptinit && promptinit
autoload -Uz colors	&& colors

setopt COMPLETE_ALIASES

# Always rebuild cache
zstyle ':completion:*' rehash true

# Arrow driven interface
zstyle ':completion:*' menu select

