#! /usr/bin/env zsh

source "$HOME/.config/zsh/modrc"

PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

source "$HOME/.config/aliasrc"
source "$HOME/.config/zsh/bindrc"

HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history
