#! /usr/bin/env zsh

source "$HOME/.config/zsh/modrc"

PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

if command -v startx > /dev/null && [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec startx
fi

source "$HOME/.config/env"
source "$HOME/.config/aliasrc"
source "$HOME/.config/zsh/bindrc"

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

