#! /usr/bin/env bash

if command -v startx > /dev/null && [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec startx
fi

source "$HOME/.config/bash/promptrc"
#source "$HOME/.config/env"
source "$HOME/.config/aliasrc"
export PATH=$PATH:$HOME/.local/bin/

[[ "$PS1" && -f /usr/share/bash-completion/bash_completion ]] && \
	. /usr/share/bash-completion/bash_completion
