#! /usr/bin/env bash

source "$HOME/.config/env"
source "$HOME/.config/bash/promptrc"

if [ -f /usr/share/bash-completion/bash_completion ]; then
    source /usr/share/bash-completion/bash_completion
fi

alias l="ls"
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias open="xdg-open"

distro() {
    if [ -f /etc/os-release ]; then
        echo "$(source /etc/os-release; echo "$NAME")"
    else
        echo "Unknown"
    fi
}
