#! /usr/bin/env bash

RED="\[\e[1;31m\]"
ORANGE="\[\e[1;33m\]"
GREEN="\[\e[1;32m\]"
BLUE="\[\e[1;94m\]"
PURPLE="\[\e[1;35m\]"
CLEAR="\[\e[0m\]"

if [ "$EUID" = 0 ]; then
    PS1="${RED}[\u@\h \w]${CLEAR}# "
else
    PS1="${RED}[${ORANGE}\u${GREEN}@${BLUE}\h ${PURPLE}\w${RED}]${CLEAR}$ "
fi

unset RED ORANGE GREEN BLUE PURPLE RED CLEAR
