#! /bin/bash

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

export CHROME_EXECUTABLE=/usr/bin/chromium

alias l="ls"
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias open="xdg-open"

pdfbuild() {
	latexmk -xelatex $1
	latexmk -c
}
